### ISSUE TITLE
Not updating when props change

### ISSUE THREAD

**Issue by acomito** [AndrewGHC/react-trix-editor#1]
This thing is awesome! 

My only issue is getting the editor to update when props change. Also, I'm building a collaborative editor, so I'd need a value prop (or to have the component rerender when initialValue prop changes)

**Comment by AndrewWalsh** [comment]
Hey Acomito!

To update the state of the text editor you'll need to use Trix's editor API which you can access with the onEditor callback. Please see https://github.com/basecamp/trix/issues/344 for an example of inserting a new value into the text editor. I've previously solved this issue with the simple code below (assuming you're storing the onEditor callback in a state variable called 'editor'):

`this.state.editor.loadHTML(newHtmlText);`

Keep in mind that the onEditor prop will be called asynchronously once Trix initialises.

**Comment by acomito** [comment]
thanks @AndrewGHC! I'll give it a try.

**Comment by acomito** [comment]
Okay so, I am so this is almost working, but it is resetting the cursor when updating:

http://g.recordit.co/MCyNaNF5Kt.gif

```
class MyEditor extends React.Component{
  constructor(props){
    super(props);
    this.handleChange = this.handleChange.bind(this);
    this.saveText = debounce(900, this.saveText);
    this.storeEditor = this.storeEditor.bind(this);
    this.state = {
      typing: false,
      saving: false,
      editor: {}
    };
  }
  storeEditor(editor){
    this.setState({editor: editor});
  }
  saveText(value){
    this.setState({saving: true, typing: false});
    const doneSaving = () => this.setState({saving: false});
    Meteor.call('documents.updateText', value, this.props.thisDocument._id, function(error, response){
      if (error) { console.log(error); return; }
      doneSaving();
    });
  }
  componentWillReceiveProps(nextProps){
    this.state.editor.loadHTML(nextProps.thisDocument.body);
  }
  handleChange(value) {
      this.setState({typing: true});
      this.saveText(value);
  }
  render(){
    const { thisDocument } = this.props;
    return <div>
      <h2>{thisDocument.title}</h2>
      <ReactTrixEditor
        onChange={this.handleChange}
        input={thisDocument._id}
        onEditor={this.storeEditor}
        initialValue={thisDocument && thisDocument.body ? thisDocument.body : ''}
      />
      {this.state.typing && <p>typing...</p>}
      {this.state.saving && <p>saving...</p>}
    </div>
  }

}
```

**Comment by AndrewWalsh** [comment]
I believe a fix for this as described here https://github.com/basecamp/trix/issues/138 would be:

`this.state.editor.setSelectedRange(this.state.editor.getDocument().toString().length -1)`

This should be done after you call loadHTML in the componentWillReceiveProps method. Think the problem here is that Trix does not save the cursor position on calling loadHTML, and since you've focus during the transition, you're seeing the cursor reset.

**Comment by acomito** [comment]
Thanks for taking the time to respond!
