### ISSUE TITLE
Best way to connect to trix events?

### ISSUE THREAD

**Issue by acomito** [AndrewGHC/react-trix-editor#2]
is there a best practice for listening to trix [events](https://github.com/basecamp/trix#observing-editor-changes)?

or should I implement something like [react-event-listener](https://www.npmjs.com/package/react-event-listener)?

**Comment by AndrewWalsh** [comment]
Editor.element contains the element and you can attach an event listener to that as below:

`this.state.editor.element.addEventListener('trix-change', () => console.log('example'))`

**Comment by acomito** [comment]
Thanks @AndrewGHC! 

Where are the some of the other main methods located?

e.g. 

`element.editor.insertString("Hello")`

this is coming up as not a function:

`this.state.editor.insertString("")`

I'm basically looking to reset the editor value. If it matters, I'm using a string of HTML in the body instead just a string.

**Comment by AndrewWalsh** [comment]
All methods should be available to the editor call back. All this component does is return the editor object when Trix initialises. It might be worth simply logging the editor and following the prototype chain to double check that's a valid method, as many of them are undocumented.
